on:
  push:
    paths:
      - 'bot/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bot_image


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build JAR
        run: mvn -DskipTests=true package -pl bot -am
      - name: Build Image
        run: docker build -q -t bot_image . -f bot.Dockerfile
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: docker push ghcr.io/arsiharsi/$IMAGE_NAME


